namespace: ansible
name: content_builder
version: 0.0.0
readme: README.md
authors:
  - Brad Thornton (@cidrblock)
  - Nilashish Chakraborty (@NilashishC)
description: A collection to scaffold Ansible content.
license_file: LICENSE
tags: []
dependencies:
  "ansible.netcommon": ">=3.0.0"
  "ansible.utils": ">=2.6.1"
repository: https://github.com/ansible-collections/ansible.content_builder
issues: https://github.com/ansible-collections/ansible.content_builder/issues
