namespace: ansible
name: plugin_builder
version: 0.0.0
readme: README.md
authors:
  - Brad Thornton (@cidrblock)
  - Nilashish Chakraborty (@NilashishC)
description: A collection to scaffold Ansible plugins.
license_file: LICENSE
tags: []
dependencies:
  "ansible.utils": ">=2.6.1"
repository: https://github.com/ansible-collections/ansible.plugin_builder
issues: https://github.com/ansible-collections/ansible.plugin_builder/issues
