---
- name: Debug message
  ansible.builtin.debug:
    msg: "Performing all common pre-tasks for scaffolding Network modules"

- name: Set required facts
  ansible.builtin.set_fact:
    resource: "{{ plugin['resource'] }}"
    rm_documentation: "docstring"

- name: Set/reset directory paths
  ansible.builtin.set_fact:
    resource_module_directories:
      - .github
      - .github/workflows
      - changelogs
      - plugins
      - plugins/filter
      - roles
      - roles/run
      - roles/run/defaults
      - roles/run/handlers
      - roles/run/tasks
      - roles/run/tasks/includes
      - roles/run/tasks/includes/health_checks
      - roles/run/tasks/includes/health_checks/templates
      - roles/run/vars

- name: "Create the resource module directory structure"
  ansible.builtin.file:
    path: "{{ parent_directory }}/{{ item }}"
    state: directory
  with_items: "{{ resource_module_directories }}"

- name: Touch the __init__.py in each directory
  ansible.builtin.copy:
    content: ""
    dest: "{{ parent_directory }}/{{ item }}/__init__.py"
    force: false
  with_items: "{{ resource_module_directories }}"

- name: Copy GH config
  ansible.builtin.copy:
    src: "workflows/"
    dest: "{{ parent_directory }}/.github/workflows"
    force: false

- name: Copy changelog config
  ansible.builtin.copy:
    src: "changelogs/"
    dest: "{{ parent_directory }}/changelogs"
    force: false

- name: Copy project config files
  ansible.builtin.copy:
    src: "project_config_files/"
    dest: "{{ parent_directory }}"
    force: false

- name: Copy health_check parsers
  ansible.builtin.copy:
    src: "health_checks/templates/"
    dest: "{{ parent_directory }}/roles/run/tasks/includes/health_checks/templates"
    force: false

- name: copy health_check.yaml
  ansible.builtin.copy:
    src: "health_check.yaml"
    dest: "{{ parent_directory }}/roles/run/tasks/includes/health_check.yaml"
    force: false

- name: Debug message
  ansible.builtin.debug:
    msg: "Completed all common pre-tasks for scaffolding Network validated content"

- name: Set required template facts
  ansible.builtin.set_fact:
    resource_module_templates:
      - source: plugin_directory/plugins/filter/health_check_view.py.j2
        destination: "{{ parent_directory }}/plugins/filter/health_check_view.py"
        overwrite: false
      - source: roles_directory/roles/tasks/includes/deploy.yaml.j2
        destination: "{{ parent_directory }}/roles/run/tasks/includes/deploy.yaml"
        overwrite: false
      - source: roles_directory/roles/tasks/includes/detect.yaml.j2
        destination: "{{ parent_directory }}/roles/run/tasks/includes/detect.yaml"
        overwrite: false
      - source: roles_directory/roles/tasks/includes/gather.yaml.j2
        destination: "{{ parent_directory }}/roles/run/tasks/includes/gather.yaml"
        overwrite: false
      - source: roles_directory/roles/tasks/includes/persist.yaml.j2
        destination: "{{ parent_directory }}/roles/run/tasks/includes/persist.yaml"
        overwrite: true
      - source: roles_directory/roles/tasks/includes/remediate.yaml.j2
        destination: "{{ parent_directory }}/roles/run/tasks/includes/remediate.yaml"
        overwrite: false
      - source: roles_directory/main.yaml.j2
        destination: "{{ parent_directory }}/roles/run/tasks/main.yaml"
        overwrite: true
      - source: CHANGELOG.rst.j2
        destination: "{{ parent_directory }}/CHANGELOG.rst"
        overwrite: true
      - source: config.yaml.j2
        destination: "{{ parent_directory }}/changelogs/config.yaml"
        overwrite: true
      - source: galaxy.yml.j2
        destination: "{{ parent_directory }}/galaxy.yml"
        overwrite: true
      

- name: Template each of the files
  ansible.builtin.include_tasks: template.yml
  with_items: "{{ resource_module_templates }}"
  loop_control:
    loop_var: template

