---
- name: Get the CURRENT WORKING DIR
  ansible.builtin.command: "pwd"
  register: dir
  changed_when: false

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: tmp_directory

- name: EXECUTE the python script
  ansible.builtin.command: python3 "{{ role_path }}"/templates/doc_generator.py "{{ plugin['rm_swagger_json'] }}"
    "{{ plugin['api_object_path'] }}"
    "{{ plugin['name'] }}"
    "{{ plugin['module_version'] }}"
    "{{ plugin['resource'] }}"
    "{{ collection['namespace'] }}"
    "{{ collection['name'] }}"
    "{{ plugin['unique_key'] }}"
    "{{ plugin['author'] }}"
    "{{ tmp_directory["path"] }}"
  delegate_to: 127.0.0.1
  run_once: true
  changed_when: false

- name: Create a vars temp directory
  ansible.builtin.file:
    path: "{{ tmp_directory['path'] }}/vars"
    state: directory
    mode: 0755

- name: Display multiple file contents
  ansible.builtin.debug:
    var: item
  with_file:
    - "{{ tmp_directory['path'] }}/data.yml"
    - "{{ tmp_directory['path'] }}/params.json"
  register: test

- name: Copy the MODULE DOC
  ansible.builtin.copy:
    content: "{{ test['results'][0]['item'] }}"
    dest: "{{ tmp_directory['path'] }}/vars/data.yaml"

- name: Copy the MODULE PARAM DICT
  ansible.builtin.copy:
    content: "{{ test['results'][1]['item'] }}"
    dest: "{{ tmp_directory['path'] }}/vars/module_params_dict.json"

- name: Extract DOCUMENTATION from source (for new module)
  ansible.builtin.set_fact:
    rm_documentation: "{{ test['results'][0]['item'] }}"
  when: test is defined

- name: Extract MODULE PARAMS Dict from source (for new module)
  ansible.builtin.set_fact:
    module_params_dict: "{{ test['results'][1]['item'] }}"
  when: test is defined

- name: Get the API object
  ansible.builtin.set_fact:
    api_object: "api/{{ plugin['api_object_path'].split('/')[1] | default('default') }}"

- name: Template each of the files
  ansible.builtin.include_tasks: template.yaml
  with_items: "{{ resource_module_templates }}"
  loop_control:
    loop_var: template

- name: Delete TEMP data files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tmp_directory['path'] }}/vars/data.yaml"
    - "{{ tmp_directory['path'] }}/vars/module_params_dict.json"
