---
- name: Set required facts
  ansible.builtin.set_fact:
    resource: "{{ plugin['resource'] }}"
    rm_documentation: "{{ docstring }}"

- name: Set required template facts
  ansible.builtin.set_fact:
    resource_module_templates:
      - source: module_directory/network_os/network_os_resource.py.j2
        destination: "{{ parent_directory }}/modules/{{ plugin['name'] }}.py"
        overwrite: true
      - source: module_directory/network_os/network_os_facts.py.j2
        destination: "{{ parent_directory }}/modules/{{ network_os }}_facts.py"
        overwrite: false
      - source: module_utils/network_os/argspec/facts/facts.py.j2
        destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/argspec/facts/facts.py"
        overwrite: false
      - source: module_utils/network_os/argspec/resource/resource.py.j2
        destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/argspec/{{ resource }}/{{ resource }}.py"
        overwrite: true
      - source: module_utils/network_os/config/resource/resource.py.j2
        destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/config/{{ resource }}/{{ resource }}.py"
        overwrite: false
      - source: module_utils/network_os/facts/facts.py.j2
        destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/facts/facts.py"
        overwrite: false
      - source: module_utils/network_os/facts/resource/resource.py.j2
        destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/facts/{{ resource }}/{{ resource }}.py"
        overwrite: false
      - source: module_utils/network_os/rm_templates/resource.py.j2
        destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/rm_templates/{{ resource }}.py"
        overwrite: false
      - source: module_utils/network_os/utils/utils.py.j2
        destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/utils/utils.py"
        overwrite: false

- name: Invoking network base to build argspec and touch common files
  ansible.builtin.include_role:
    name: module_network_base

- name: Template each of the files
  ansible.builtin.include: template.yml
  with_items: "{{ resource_module_templates }}"
  loop_control:
    loop_var: template
